### ISSUE TITLE
Launch stable version aka 1.0.0

### ISSUE THREAD

**Issue by WolfgangVing** [WolfgangVing/cli-readme-file-creator#7]
To be comfortable enough to launch this project as 1.0 stable version,  I would like to suffice some requirements -established by myself-, which can undergo changes.
There is also room of creating a website to present the idea. 

---
<h3> TODO </h3>

- [ ] Polish documentation #2 
- [ ] Add reserved keywords #5 
- [ ] Reduce the size of the project #4
- [ ] Do some tests #3 
- [ ] At least 3 templates natively
